- name: Install MySQL Server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Start MySQl Server service
  ansible.builtin.systemd_service:
    state: restarted
    name: mysqld
    enabled: true

- name: Setup MySQL Root Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1

