- name: Add roboshop application user
  ansible.builtin.user:
    name: roboshop

- name: Remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
    dest: /app
    remote_src: yes

