- name: Install NodeJS 20
  ansible.builtin.dnf:
    name: '@nodejs:20'
    state: present

- name: Load app pre-reqs
  ansible.builtin.import_tasks: app_prereqs.yml

- name: Install packages based on package.json.
  community.general.npm:
    path: /app

- name: Load systemd
  ansible.builtin.import_tasks: systemd.yml
