- name: Install Python and gcc
  ansible.builtin.dnf:
    name:
      - python3
      - gcc
      - python3-devel
    state: present

- name: Load app pre-reqs
  ansible.builtin.import_tasks: app_prereqs.yml

- name: Install specified python requirements
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /app

- name: Load systemd
  ansible.builtin.import_tasks: systemd.yml

