- name: Copy {{ component }} service file
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: Start {{ component }} service
  ansible.builtin.systemd_service:
    state: restarted
    name: "{{ component }}"
    enabled: true
    daemon_reload: true

